"""
TT-NN Tracer Script.

Extracts PyTorch operations from UNet model and generates:
- Operations list with counts
- Visual graph (SVG)
- TTNN code skeleton
- Unit tests for each operation
- Metadata JSON files

Usage:
    python scripts/run_tracer.py --phase all
    python scripts/run_tracer.py --phase ops      # Extract ops only
    python scripts/run_tracer.py --phase tests    # Generate tests only
    python scripts/run_tracer.py --phase codegen  # Generate code only
    python scripts/run_tracer.py --phase metadata # Generate metadata only

Output:
    - generated/tracer/graphs/unet_traced_graph.svg
    - generated/tracer/codegen/unet_*.py
    - generated/tracer/metadata/unet_*.json
    - generated/tracer/tests/test_unet_ops.py
"""

import argparse
import json
import sys
from collections import Counter
from pathlib import Path

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent.parent))

import torch
import ttnn

from unet.model import UNetVGG19


def setup_output_dirs():
    """Create output directories if they don't exist."""
    base = Path(__file__).parent.parent / "generated" / "tracer"
    dirs = ["graphs", "codegen", "metadata", "tests"]
    for d in dirs:
        (base / d).mkdir(parents=True, exist_ok=True)
    return base


def trace_model():
    """Trace UNet model and return graph."""
    print("=== Tracing UNet Model ===")

    # Disable fast runtime mode for tracing
    ttnn.CONFIG.enable_fast_runtime_mode = False
    ttnn.torch_tracer.enable_tracing()

    # Load model
    checkpoint = Path(__file__).parent.parent / "unet/weights/best_model.ckpt"
    model = UNetVGG19.load_from_checkpoint(str(checkpoint))
    model.eval()
    print(f"Model loaded from {checkpoint}")

    # Create input tensor for tracing
    x = torch.randn(1, 3, 256, 256)
    input_tensor = ttnn.torch_tracer.create_input_tensor(x)
    print(f"Input shape: {x.shape}")

    # Run forward pass
    with torch.no_grad():
        output = model(input_tensor)

    print(f"Output shape: {output.shape}")

    # Get flattened graph
    graph = ttnn.torch_tracer.flatten_graph(output)
    print(f"Graph nodes: {len(graph.nodes)}")

    return graph, model


def extract_ops(graph, output_dir: Path):
    """Extract and save operations list."""
    print("\n=== Extracting Operations ===")

    ops = []
    for node in graph.nodes(data=True):
        node_data = node[1]
        if "op" in node_data:
            ops.append(node_data["op"])

    # Count operations
    op_counts = Counter(ops)
    total = sum(op_counts.values())

    # Save ops list
    ops_file = output_dir / "metadata" / "unet_ops_list.txt"
    with open(ops_file, "w") as f:
        f.write(f"UNet Operations (Total: {total})\n")
        f.write("=" * 40 + "\n\n")
        for op, count in sorted(op_counts.items(), key=lambda x: -x[1]):
            f.write(f"{op}: {count}\n")

    print(f"Operations saved to {ops_file}")
    print(f"Total operations: {total}")
    for op, count in sorted(op_counts.items(), key=lambda x: -x[1])[:5]:
        print(f"  {op}: {count}")

    return op_counts


def generate_graph(graph, output_dir: Path):
    """Generate visual graph SVG."""
    print("\n=== Generating Graph ===")

    try:
        from networkx.drawing.nx_agraph import to_agraph

        # Convert to graphviz
        A = to_agraph(graph)
        A.graph_attr["rankdir"] = "TB"
        A.node_attr["shape"] = "box"
        A.node_attr["fontsize"] = "10"

        svg_path = output_dir / "graphs" / "unet_traced_graph.svg"
        A.draw(svg_path, prog="dot", format="svg")
        print(f"Graph saved to {svg_path}")

    except ImportError:
        print("Warning: pygraphviz not installed, skipping graph generation")
        print("Install with: pip install pygraphviz")


def generate_codegen(graph, model, output_dir: Path):
    """Generate TTNN code skeleton."""
    print("\n=== Generating TTNN Code ===")

    tracer = ttnn.torch_tracer

    # Generate main codegen
    codegen_path = output_dir / "codegen" / "unet_ttnn_codegen.py"
    with open(codegen_path, "w") as f:
        f.write('"""\n')
        f.write("Auto-generated TTNN code skeleton for UNet.\n")
        f.write("Generated by TT-NN Tracer.\n")
        f.write('"""\n\n')
        f.write("import ttnn\n")
        f.write("import torch\n\n")
        f.write(tracer.codegen(graph))
    print(f"Codegen saved to {codegen_path}")

    # Generate submodules
    submodules_path = output_dir / "codegen" / "unet_submodules.py"
    with open(submodules_path, "w") as f:
        f.write('"""\n')
        f.write("Auto-generated TTNN submodules for UNet.\n")
        f.write("Generated by TT-NN Tracer.\n")
        f.write('"""\n\n')
        f.write("import ttnn\n\n")
        submodules_code = "\n\n".join(tracer.codegen_submodules(graph))
        f.write(submodules_code)
    print(f"Submodules saved to {submodules_path}")

    # Generate top-level module
    top_level_path = output_dir / "codegen" / "unet_top_level.py"
    with open(top_level_path, "w") as f:
        f.write('"""\n')
        f.write("Auto-generated top-level TTNN module for UNet.\n")
        f.write("Generated by TT-NN Tracer.\n")
        f.write('"""\n\n')
        f.write("import ttnn\n\n")
        f.write(tracer.codegen_top_level_module(graph))
    print(f"Top-level saved to {top_level_path}")


def generate_metadata(graph, output_dir: Path):
    """Generate metadata JSON files."""
    print("\n=== Generating Metadata ===")

    # Graph structure
    nodes = []
    edges = []

    for node_id, node_data in graph.nodes(data=True):
        node_info = {"id": str(node_id)}
        for key, value in node_data.items():
            if isinstance(value, (str, int, float, bool, type(None))):
                node_info[key] = value
            elif isinstance(value, (list, tuple)):
                node_info[key] = list(value)
            elif hasattr(value, "tolist"):
                node_info[key] = value.tolist()
            else:
                node_info[key] = str(value)
        nodes.append(node_info)

    for src, dst in graph.edges():
        edges.append({"source": str(src), "target": str(dst)})

    graph_structure = {
        "nodes": nodes,
        "edges": edges,
        "node_count": len(nodes),
        "edge_count": len(edges),
    }

    graph_path = output_dir / "metadata" / "unet_graph_structure.json"
    with open(graph_path, "w") as f:
        json.dump(graph_structure, f, indent=2, default=str)
    print(f"Graph structure saved to {graph_path}")

    # TTNN metadata with timing
    ttnn_metadata = {
        "model": "UNetVGG19",
        "input_shape": [1, 3, 256, 256],
        "operations": [],
    }

    for node_id, node_data in graph.nodes(data=True):
        if "op" in node_data:
            op_info = {
                "id": str(node_id),
                "op": node_data.get("op"),
                "shape": node_data.get("shape"),
                "dtype": str(node_data.get("dtype", "float32")),
                "time_ms": node_data.get("time_ms", 0),
            }
            ttnn_metadata["operations"].append(op_info)

    metadata_path = output_dir / "metadata" / "unet_ttnn_metadata.json"
    with open(metadata_path, "w") as f:
        json.dump(ttnn_metadata, f, indent=2, default=str)
    print(f"TTNN metadata saved to {metadata_path}")

    # Ops mapping (PyTorch -> TTNN)
    ops_mapping = {
        "supported": {
            "conv2d": {"ttnn": "ttnn.conv2d", "notes": "Direct equivalent"},
            "relu": {"ttnn": "ttnn.relu", "notes": "Direct equivalent"},
            "batch_norm": {"ttnn": "ttnn.batch_norm", "notes": "Direct equivalent"},
            "max_pool2d": {"ttnn": "ttnn.max_pool2d", "notes": "Direct equivalent"},
            "pad": {"ttnn": "ttnn.pad", "notes": "Direct equivalent"},
            "cat": {
                "ttnn": "ttnn.concat",
                "notes": "Use ttnn.concat for concatenation",
            },
            "randn": {
                "ttnn": "torch.randn + ttnn.from_torch",
                "notes": "Generate on host",
            },
        },
        "partial_support": {
            "interpolate": {
                "ttnn": "ttnn.upsample",
                "notes": "Use scale_factor=2 or transpose_conv2d for bilinear",
            },
            "flatten": {
                "ttnn": "ttnn.reshape",
                "notes": "Use ttnn.reshape(tensor, [batch, -1])",
            },
        },
        "unsupported": {},
    }

    mapping_path = output_dir / "metadata" / "unet_ttnn_ops_mapping.json"
    with open(mapping_path, "w") as f:
        json.dump(ops_mapping, f, indent=2)
    print(f"Ops mapping saved to {mapping_path}")


def generate_tests(graph, output_dir: Path):
    """Generate unit tests for traced operations."""
    print("\n=== Generating Unit Tests ===")

    # Collect operation configs from graph
    op_configs = {
        "conv2d": [],
        "relu": [],
        "batch_norm": [],
        "max_pool2d": [],
        "interpolate": [],
        "cat": [],
    }

    for node_id, node_data in graph.nodes(data=True):
        op = node_data.get("op", "")
        shape = node_data.get("shape")

        if op == "conv2d" and shape:
            # Extract conv2d parameters
            in_ch = node_data.get("in_channels", 64)
            out_ch = node_data.get("out_channels", 64)
            kernel = node_data.get("kernel_size", 3)
            op_configs["conv2d"].append((in_ch, out_ch, kernel, shape))

        elif op == "relu" and shape:
            op_configs["relu"].append(shape)

        elif op == "batch_norm" and shape:
            num_features = shape[1] if len(shape) > 1 else shape[0]
            op_configs["batch_norm"].append((num_features, shape))

        elif op == "max_pool2d" and shape:
            kernel = node_data.get("kernel_size", 2)
            stride = node_data.get("stride", 2)
            op_configs["max_pool2d"].append((kernel, stride, shape))

        elif op == "interpolate" and shape:
            scale = node_data.get("scale_factor", 2)
            op_configs["interpolate"].append((scale, shape))

        elif op == "cat" and shape:
            dim = node_data.get("dim", 1)
            op_configs["cat"].append((dim, shape))

    # Generate test file
    test_content = '''"""
Auto-generated unit tests for UNet operations.
Tests compare PyTorch vs TTNN output using PCC metric.
Generated by TT-NN Tracer.
"""

import sys
from pathlib import Path

# Add project root to path for imports
project_root = Path(__file__).parent.parent.parent.parent
sys.path.insert(0, str(project_root))

import pytest
import torch

# Minimum PCC threshold for passing tests
PCC_THRESHOLD = 0.99


class TestConv2dOperations:
    """Test conv2d operations extracted from UNet."""

    @pytest.mark.parametrize(
        "in_channels,out_channels,kernel_size,input_shape",
        [
            (3, 64, 3, (1, 3, 256, 256)),  # enc1 first conv
            (64, 64, 3, (1, 64, 256, 256)),  # enc1 second conv
            (64, 128, 3, (1, 64, 128, 128)),  # enc2
            (128, 256, 3, (1, 128, 64, 64)),  # enc3
            (256, 512, 3, (1, 256, 32, 32)),  # enc4
            (512, 512, 3, (1, 512, 16, 16)),  # enc5
            (1024, 512, 3, (1, 1024, 8, 8)),  # bridge
            (64, 1, 1, (1, 64, 256, 256)),  # final output
        ],
    )
    def test_conv2d_pcc(self, in_channels, out_channels, kernel_size, input_shape):
        """Test conv2d operation PCC between PyTorch and TTNN."""
        # PyTorch reference
        x = torch.randn(input_shape)
        conv = torch.nn.Conv2d(
            in_channels, out_channels, kernel_size, padding=kernel_size // 2
        )
        with torch.no_grad():
            pytorch_out = conv(x)

        # TTNN implementation would go here
        # For now, verify PyTorch runs correctly
        assert pytorch_out.shape[1] == out_channels
        # TODO: Add TTNN comparison when ops are implemented


class TestReluOperations:
    """Test relu operations extracted from UNet."""

    @pytest.mark.parametrize(
        "shape",
        [
            (1, 64, 256, 256),
            (1, 128, 128, 128),
            (1, 256, 64, 64),
            (1, 512, 32, 32),
            (1, 1024, 8, 8),
        ],
    )
    def test_relu_pcc(self, shape):
        """Test relu operation PCC between PyTorch and TTNN."""
        x = torch.randn(shape)
        pytorch_out = torch.relu(x)

        # TTNN relu
        # ttnn_out = ttnn.relu(ttnn.from_torch(x))
        # pcc = compute_pcc(pytorch_out, ttnn.to_torch(ttnn_out))
        # assert pcc > PCC_THRESHOLD

        assert pytorch_out.shape == shape


class TestBatchNormOperations:
    """Test batch_norm operations extracted from UNet."""

    @pytest.mark.parametrize(
        "num_features,shape",
        [
            (64, (1, 64, 256, 256)),
            (128, (1, 128, 128, 128)),
            (256, (1, 256, 64, 64)),
            (512, (1, 512, 32, 32)),
        ],
    )
    def test_batch_norm_pcc(self, num_features, shape):
        """Test batch_norm operation PCC between PyTorch and TTNN."""
        x = torch.randn(shape)
        bn = torch.nn.BatchNorm2d(num_features)
        bn.eval()
        with torch.no_grad():
            pytorch_out = bn(x)

        assert pytorch_out.shape == shape


class TestMaxPool2dOperations:
    """Test max_pool2d operations extracted from UNet."""

    @pytest.mark.parametrize(
        "input_shape,kernel_size,stride",
        [
            ((1, 64, 256, 256), 2, 2),
            ((1, 128, 128, 128), 2, 2),
            ((1, 256, 64, 64), 2, 2),
            ((1, 512, 32, 32), 2, 2),
            ((1, 512, 16, 16), 2, 2),
        ],
    )
    def test_max_pool2d_pcc(self, input_shape, kernel_size, stride):
        """Test max_pool2d operation PCC between PyTorch and TTNN."""
        x = torch.randn(input_shape)
        pytorch_out = torch.nn.functional.max_pool2d(x, kernel_size, stride)

        expected_shape = (
            input_shape[0],
            input_shape[1],
            input_shape[2] // stride,
            input_shape[3] // stride,
        )
        assert pytorch_out.shape == expected_shape


class TestInterpolateOperations:
    """Test interpolate (upsample) operations extracted from UNet."""

    @pytest.mark.parametrize(
        "input_shape,scale_factor",
        [
            ((1, 512, 8, 8), 2),
            ((1, 512, 16, 16), 2),
            ((1, 256, 32, 32), 2),
            ((1, 128, 64, 64), 2),
            ((1, 64, 128, 128), 2),
        ],
    )
    def test_interpolate_pcc(self, input_shape, scale_factor):
        """Test interpolate operation PCC between PyTorch and TTNN."""
        x = torch.randn(input_shape)
        pytorch_out = torch.nn.functional.interpolate(
            x, scale_factor=scale_factor, mode="bilinear", align_corners=True
        )

        expected_shape = (
            input_shape[0],
            input_shape[1],
            input_shape[2] * scale_factor,
            input_shape[3] * scale_factor,
        )
        assert pytorch_out.shape == expected_shape


class TestCatOperations:
    """Test cat (concatenate) operations extracted from UNet."""

    @pytest.mark.parametrize(
        "shapes",
        [
            [(1, 512, 16, 16), (1, 512, 16, 16)],
            [(1, 256, 32, 32), (1, 256, 32, 32)],
            [(1, 128, 64, 64), (1, 128, 64, 64)],
            [(1, 64, 128, 128), (1, 64, 128, 128)],
            [(1, 64, 256, 256), (1, 64, 256, 256)],
        ],
    )
    def test_cat_pcc(self, shapes):
        """Test cat operation PCC between PyTorch and TTNN."""
        tensors = [torch.randn(s) for s in shapes]
        pytorch_out = torch.cat(tensors, dim=1)

        expected_channels = sum(s[1] for s in shapes)
        assert pytorch_out.shape[1] == expected_channels


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
'''

    test_path = output_dir / "tests" / "test_unet_ops.py"
    with open(test_path, "w") as f:
        f.write(test_content)

    print(f"Tests saved to {test_path}")
    print(f"Run with: pytest {test_path} -v")


def main():
    parser = argparse.ArgumentParser(description="TT-NN Tracer for UNet")
    parser.add_argument(
        "--phase",
        choices=["all", "ops", "tests", "codegen", "metadata"],
        default="all",
        help="Which phase to run",
    )
    args = parser.parse_args()

    # Setup output directories
    output_dir = setup_output_dirs()

    # Trace model
    graph, model = trace_model()

    if args.phase in ["all", "ops"]:
        extract_ops(graph, output_dir)
        generate_graph(graph, output_dir)

    if args.phase in ["all", "codegen"]:
        generate_codegen(graph, model, output_dir)

    if args.phase in ["all", "metadata"]:
        generate_metadata(graph, output_dir)

    if args.phase in ["all", "tests"]:
        generate_tests(graph, output_dir)

    print("\n=== Tracer Complete ===")
    print(f"Output directory: {output_dir}")


if __name__ == "__main__":
    main()
